### ISSUE TITLE
Modifications to case information

### ISSUE THREAD

**Issue by sameerasrg** [ayubowan/selft_tracking_app#115]
A case should include only the following information. The same should be displayed to the user.

1. Source identified or not
2. Imported or local
3. From within a quarantine facility or from the community
4. Show the identified location
5. Do not show the location trace.

**Comment by dewmal** [comment]
Response json

{
   “id”:“1",
   “caseNumber”:“dhis/wp/cmb/123",
   “isLocal”:true,
   “detectedFrom”:“quarantine/home”,
   “locations”:[
      {
         “date”:“2020-03-03",
         “area”:“”,
         “longitude”:“”,
         “latitude”:“”
      }
   ],
   “message”:“This is a test message”,
   “created”:“2020-03-20 18:23:05"
}
