### ISSUE TITLE
Notification for new news item not received when user is using the app and in a different tab other than news tab

### ISSUE THREAD

**Issue by aravinth9019** [ayubowan/selft_tracking_app#128]
**Steps to reproduce:**
1. Open the app
2. Navigate to any tab other than news tab
3. Trigger a new news item from back-end
4. Verify if the user gets a notification

**Expected result:**
User should get a notification
On clicking the notification user should be navigated to the news tab

**Actual result:**
User does not get any notifications

**Comment by dewmal** [comment]
Handling app on background seems like an issue

https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages

The Dart VM does not run while the app is in background. That means you have to handle notifications and data messages in native code (Java/Kotlin/ObjectiveC/Swift).

To do this on Android, refer to the official documentation.

You will probably have to remove the firebase_messaging plugin and do all the message handling manually. To send the notification content to your flutter app (while it is in foreground), use platform channels.

It really helps to look at the source code of the firebase_messaging plugin to see what happens on the native side.

**Comment by aravinth9019** [comment]
It was decided not to introduce a notification. The user is navigated to the news tab as soon as a piece of new news is published.
