### ISSUE TITLE
Incorrect application version number is displayed on the language selection screen

### ISSUE THREAD

**Issue by aravinth9019** [ayubowan/selft_tracking_app#130]
**Steps to reproduce:**
1. Open the app
2. Click on language selection from the menu
3. Verify the app version number

**Expected result:**
Latest app version should be displayed

**Actual result:**
Version 1.0.0 is displayed

![image](https://user-images.githubusercontent.com/62384060/77252934-430f2800-6c7d-11ea-80e3-106a3c42e09c.png)

**Comment by dewmal** [comment]
This should fixed by manual before the production release.

**Comment by aravinth9019** [comment]
The correct version number is displayed when electing language.
The bug is fixed.
