### ISSUE TITLE
Enable My location tab

### ISSUE THREAD

**Issue by aravinth9019** [ayubowan/selft_tracking_app#150]
- Enable My location tab in the mobile app
- If the user has not provided access to the location tab, the user should be promoted for location access every time the user navigates to My location tab

**Comment by aravinth9019** [comment]
My location tab is enabled.

However, location data is not displayed accurately in the app. I used a fake GPS app to mimic my location across various areas. While testing I found out that the map always displays only the last location. It does not show the history of all locations I mimicked as traveled.

Need to fix above issue.

**Comment by dewmal** [comment]
Fixed that
