### ISSUE TITLE
Case list elements are not translated

### ISSUE THREAD

**Issue by aravinth9019** [ayubowan/selft_tracking_app#158]
Following elements in case list is not translated 
- Foreign/Local label
- Community label
- Reported Locations header
- Register button

**Expected result:**
Above elements should be translated for both Sinhala and Tamil

![image](https://user-images.githubusercontent.com/62384060/77324405-b1ff8600-6d3c-11ea-93aa-6ad23a449219.png)

**Comment by dewmal** [comment]
fixed in v1.12.5
