### ISSUE TITLE
Text in News Screen is not shown 

### ISSUE THREAD

**Issue by avinath1998** [ayubowan/selft_tracking_app#33]
The text in the news article screen is missing or not being shown. A screenshot has been attached.
The articles are being correctly fetched but not being shown correctly 

![Screenshot_2020-03-16-17-42-41-677_app ceylon selftrackingapp](https://user-images.githubusercontent.com/45346334/76757476-a8f73d80-67ad-11ea-99b7-876f4b47c046.jpg)

**Comment by dewmal** [comment]
Fixed in new UI
