### ISSUE TITLE
Scope change: Provide Infection Related Information Instead

### ISSUE THREAD

**Issue by bhagyas** [ayubowan/selft_tracking_app#41]
This project seems to be an attempt to illegally enforce surveillance on Sri Lankan citizens. 

I suggest providing infection related information through this attempt instead.

**Comment by sadika9** [comment]
We do not share identifiable information with anyone. All the data we collect anonymized before leaving the app. Also location data does not leave the app unless user explicitly allow it through the app.

For more details see following:
- [COVID-19 — It is time to press Shift+Delete](https://medium.com/@dewmalnilanka/covid-19-it-is-time-to-pres-ctrl-d-b5255245db92)
- [Privacy Policy](https://docs.google.com/document/d/1cp5iMi-V33mLTUk6DMk8gJgELQR1ni_OsbhavpgEpOI/edit?usp=sharing)

**Comment by sanjiva** [comment]
Bhagya you've made this same ridiculous comment on the document. Read what it does- it DOES NOT upload any location info to anyone.

Don't try to make something out of nothing please. I assume u r a techie; this is not the time to make false assertions for whatever reason (that I cannot figure out).
