### ISSUE TITLE
Allow registration with DHIS2

### ISSUE THREAD

**Issue by sadika9** [ayubowan/selft_tracking_app#6]
@FahimF doing this task

**Comment by FahimF** [comment]
The UI and localisation code is complete. Need backend API in place in order to be able to actually call the registration API and to test it.

**Comment by sadika9** [comment]
Use covid19.egreen.io:8000 to access API

**Comment by FahimF** [comment]
@sadika9 Any information/docs on the available API calls (specifically the user registration call in this case)? My apologies if this was documented somewhere and I missed it ...

**Comment by sadika9** [comment]
See [https://github.com/azhamn/COVID-19/blob/master/readme.md](https://github.com/azhamn/COVID-19/blob/master/readme.md)
