### ISSUE TITLE
Replace stat update from Firebase Cloud config to back end service

### ISSUE THREAD

**Issue by dewmal** [ayubowan/selft_tracking_app#64]

**Comment by FahimF** [comment]
Refer to: https://github.com/ICTASL/COVID-19

Need to use the new `/dashboard/status` endpoint available here:
https://api.covid-19.health.gov.lk/application/dashboard/status

**Comment by FahimF** [comment]
I am working on this

**Comment by FahimF** [comment]
Completed as part of this PR:
https://github.com/ayubowan/selft_tracking_app/pull/92
