### ISSUE TITLE
Extra large UI components on tablets

### ISSUE THREAD

**Issue by FahimF** [ayubowan/selft_tracking_app#89]
Some of the UI components look extra large, or have too much spacing, or look lost because the text is pushed way to one side with a lot of empty space after them.
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-03-20 at 06 40 20](https://user-images.githubusercontent.com/181110/77135231-8f494500-6a90-11ea-9d62-5adf0ea2fb93.png)
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-03-20 at 06 40 39](https://user-images.githubusercontent.com/181110/77135235-940df900-6a90-11ea-8ae3-76bc589cbf4b.png)

**Comment by avinath1998** [comment]
Ill work on this issue
